import { Noto_Sans_JP } from 'next/font/google';
import './globals.css';
const noto = Noto_Sans_JP({ subsets: ['latin'], weight: '400' });

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '(no title)',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${noto.className} prose`} data-theme="light">
        {children}
      </body>
    </html>
  );
}
